Repository: plone.app.users


Branch: refs/heads/master
Date: 2024-06-06T17:48:29+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.users/commit/cd12376ff835e6fea02e6b36b4503eafe1750c4c

Fix error on personal-information page when you leave an existing portrait unchanged.

The previous release added validation, but this caused a regression.
Fixes https://github.com/plone/plone.app.users/issues/126

Files changed:
A news/126.bugfix
M plone/app/users/browser/account.py

b'diff --git a/news/126.bugfix b/news/126.bugfix\nnew file mode 100644\nindex 00000000..aeba0c57\n--- /dev/null\n+++ b/news/126.bugfix\n@@ -0,0 +1,3 @@\n+Fix error on personal-information page when you leave an existing portrait unchanged.\n+The previous release added validation, but this caused a regression.\n+[maurits]\ndiff --git a/plone/app/users/browser/account.py b/plone/app/users/browser/account.py\nindex 720e53f9..b9aa9fde 100644\n--- a/plone/app/users/browser/account.py\n+++ b/plone/app/users/browser/account.py\n@@ -21,6 +21,7 @@\n from Products.statusmessages.interfaces import IStatusMessage\n from z3c.form import button\n from z3c.form import form\n+from z3c.form.interfaces import NOT_CHANGED\n from zope import schema\n from zope.cachedescriptors.property import Lazy as lazy_property\n from zope.component import getMultiAdapter\n@@ -272,8 +273,12 @@ def validate_portrait(self, action, data):\n         SVG files are not yet supported.\n         """\n         error_keys = [error.field.getName() for error in action.form.widgets.errors]\n-        if "portrait" not in error_keys and data["portrait"] is not None:\n-            portrait = data["portrait"].open()\n+        if "portrait" in error_keys:\n+            return\n+        portrait_file = data["portrait"]\n+        if portrait_file is None or portrait_file is NOT_CHANGED:\n+            return\n+        with portrait_file.open() as portrait:\n             try:\n                 Image.open(portrait)\n             except UnidentifiedImageError:\n'

Repository: plone.app.users


Branch: refs/heads/master
Date: 2024-06-07T10:00:19-04:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.users/commit/2c8f9d018056828d61a7f8b3fd0c83c8dad980ae

Merge pull request #129 from plone/maurits-fix-portrait-not-changed

Fix error on personal-information when leaving existing portrait unchanged

Files changed:
A news/126.bugfix
M plone/app/users/browser/account.py

b'diff --git a/news/126.bugfix b/news/126.bugfix\nnew file mode 100644\nindex 00000000..aeba0c57\n--- /dev/null\n+++ b/news/126.bugfix\n@@ -0,0 +1,3 @@\n+Fix error on personal-information page when you leave an existing portrait unchanged.\n+The previous release added validation, but this caused a regression.\n+[maurits]\ndiff --git a/plone/app/users/browser/account.py b/plone/app/users/browser/account.py\nindex 720e53f9..b9aa9fde 100644\n--- a/plone/app/users/browser/account.py\n+++ b/plone/app/users/browser/account.py\n@@ -21,6 +21,7 @@\n from Products.statusmessages.interfaces import IStatusMessage\n from z3c.form import button\n from z3c.form import form\n+from z3c.form.interfaces import NOT_CHANGED\n from zope import schema\n from zope.cachedescriptors.property import Lazy as lazy_property\n from zope.component import getMultiAdapter\n@@ -272,8 +273,12 @@ def validate_portrait(self, action, data):\n         SVG files are not yet supported.\n         """\n         error_keys = [error.field.getName() for error in action.form.widgets.errors]\n-        if "portrait" not in error_keys and data["portrait"] is not None:\n-            portrait = data["portrait"].open()\n+        if "portrait" in error_keys:\n+            return\n+        portrait_file = data["portrait"]\n+        if portrait_file is None or portrait_file is NOT_CHANGED:\n+            return\n+        with portrait_file.open() as portrait:\n             try:\n                 Image.open(portrait)\n             except UnidentifiedImageError:\n'

