Repository: Products.CMFPlone


Branch: refs/heads/master
Date: 2024-10-15T22:21:08-07:00
Author: Wesley Barroso Lopes (wesleybl) <wesleybl@gmail.com>
Commit: https://github.com/plone/Products.CMFPlone/commit/9a1a62bb0ed4b208d303748700a5d0a126bd21d2

Avoid POSKeyError when commit occurs and we have savepoint that involves (#4026)

Plone Site

When ZODB handles savepoint and we have changes in Plone Site at that
savepoint, it changes the `_p_estimated_size` attribute of Plone Site.
This is an assignment to one of the special persistency attributes
(identified by an _p_ name prefix); it should happen without access to
any other attributes of obj. But obj._tree is accessed in __setattr__ of
PloneSite class and results in a ZODB load which apparently fails.

See: https://github.com/plone/plone.restapi/pull/1823#issuecomment-2402855105

Co-authored-by: Rohan Shaw &lt;86848116+rohnsha0@users.noreply.github.com&gt;

Files changed:
A news/4026.bugfix
M Products/CMFPlone/Portal.py

b'diff --git a/Products/CMFPlone/Portal.py b/Products/CMFPlone/Portal.py\nindex cbf4c91149..878872e666 100644\n--- a/Products/CMFPlone/Portal.py\n+++ b/Products/CMFPlone/Portal.py\n@@ -61,7 +61,7 @@ def __getattr__(self, name):\n \n     def __setattr__(self, name, obj):\n         # handle re setting an item as an attribute\n-        if self._tree is not None and name in self:\n+        if not name.startswith("_") and self._tree is not None and name in self:\n             del self[name]\n             self[name] = obj\n         else:\ndiff --git a/news/4026.bugfix b/news/4026.bugfix\nnew file mode 100644\nindex 0000000000..a51ab29b2e\n--- /dev/null\n+++ b/news/4026.bugfix\n@@ -0,0 +1 @@\n+Avoid POSKeyError when commit occurs and we have savepoint that involves Plone Site. @wesleybl\n'

