Repository: plone.releaser


Branch: refs/heads/master
Date: 2021-01-09T12:46:59+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/31a4b1f7e04053e76eee82024a77104a9130ec89

When reporting interesting commits, catch errors when comparing with previously ignored commit.

Fixes https://github.com/plone/plone.releaser/issues/39.

Files changed:
A news/39.bugfix
M plone/releaser/package.py

b'diff --git a/news/39.bugfix b/news/39.bugfix\nnew file mode 100644\nindex 0000000..6d96360\n--- /dev/null\n+++ b/news/39.bugfix\n@@ -0,0 +1,3 @@\n+When reporting interesting commits, catch errors when comparing with previously ignored commit.\n+Fixes `issue 39 <https://github.com/plone/plone.releaser/issues/39>`_.\n+[maurits]\ndiff --git a/plone/releaser/package.py b/plone/releaser/package.py\nindex 49046ab..cd91060 100644\n--- a/plone/releaser/package.py\n+++ b/plone/releaser/package.py\n@@ -137,8 +137,11 @@ def __call__(self, action=ACTION_INTERACTIVE):\n                         repo, latest_ignored_commit, self.source.branch\n                     )\n                 except git.exc.GitCommandError:\n-                    print("\\nCould not read commits for package {0}".format(self.name))\n-                    return\n+                    # Most likely error is that this fails:\n+                    # git rev-list latest_ignored_commit..master\n+                    # This happens when latest_ignored_commit is not on the master branch.\n+                    # See https://github.com/plone/plone.releaser/issues/39\n+                    commits_since_ignore = interesting_commits\n                 if not commits_since_ignore:\n                     # Okay, nothing interesting.\n                     self.remove()\n'

Repository: plone.releaser


Branch: refs/heads/master
Date: 2021-01-09T13:01:53+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.releaser/commit/1a54656bb5019bd70e27e1f7c4ad9e78ce36c36a

Issue 39: improve error message when git rev-list fails.

This is when comparing the current version from versions.cfg with the branch from sources.cfg.

Files changed:
M plone/releaser/package.py

b'diff --git a/plone/releaser/package.py b/plone/releaser/package.py\nindex cd91060..e5b392d 100644\n--- a/plone/releaser/package.py\n+++ b/plone/releaser/package.py\n@@ -220,7 +220,9 @@ def latest_commits(self, repo):\n         try:\n             commits = self._commits_between(repo, self.version, self.source.branch)\n         except git.exc.GitCommandError:\n-            print("\\nCould not read commits for package {0}".format(self.name))\n+            print("\\nCould not read commits between {0} and {1} for package {2}".format(\n+                self.version, self.source.branch, self.name\n+                ))\n \n         return commits\n \n'

Repository: plone.releaser


Branch: refs/heads/master
Date: 2021-01-09T13:22:48+01:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.releaser/commit/d8901a6b4269461dbe1f51eb0ead3265118ddb73

Merge pull request #40 from plone/maurits/issue-39-ignore-git-error-checking-ignored-commit

When filtering interesting commits, catch git errors

Files changed:
A news/39.bugfix
M plone/releaser/package.py

b'diff --git a/news/39.bugfix b/news/39.bugfix\nnew file mode 100644\nindex 0000000..6d96360\n--- /dev/null\n+++ b/news/39.bugfix\n@@ -0,0 +1,3 @@\n+When reporting interesting commits, catch errors when comparing with previously ignored commit.\n+Fixes `issue 39 <https://github.com/plone/plone.releaser/issues/39>`_.\n+[maurits]\ndiff --git a/plone/releaser/package.py b/plone/releaser/package.py\nindex 49046ab..e5b392d 100644\n--- a/plone/releaser/package.py\n+++ b/plone/releaser/package.py\n@@ -137,8 +137,11 @@ def __call__(self, action=ACTION_INTERACTIVE):\n                         repo, latest_ignored_commit, self.source.branch\n                     )\n                 except git.exc.GitCommandError:\n-                    print("\\nCould not read commits for package {0}".format(self.name))\n-                    return\n+                    # Most likely error is that this fails:\n+                    # git rev-list latest_ignored_commit..master\n+                    # This happens when latest_ignored_commit is not on the master branch.\n+                    # See https://github.com/plone/plone.releaser/issues/39\n+                    commits_since_ignore = interesting_commits\n                 if not commits_since_ignore:\n                     # Okay, nothing interesting.\n                     self.remove()\n@@ -217,7 +220,9 @@ def latest_commits(self, repo):\n         try:\n             commits = self._commits_between(repo, self.version, self.source.branch)\n         except git.exc.GitCommandError:\n-            print("\\nCould not read commits for package {0}".format(self.name))\n+            print("\\nCould not read commits between {0} and {1} for package {2}".format(\n+                self.version, self.source.branch, self.name\n+                ))\n \n         return commits\n \n'

