Repository: plone.recipe.zope2instance


Branch: refs/heads/master
Date: 2021-03-22T10:12:27+01:00
Author: Jens Vagelpohl (dataflake) <jens@netz.ooo>
Commit: https://github.com/plone/plone.recipe.zope2instance/commit/b071b1e0aa396f5867e9d4603a1ce500d20886a6

Fixed ``$PYTHONSTARTUP`` file support for the ``debug`` command under Python 3

Files changed:
A news/167.bugfix
M src/plone/recipe/zope2instance/ctl.py

b'diff --git a/news/167.bugfix b/news/167.bugfix\nnew file mode 100644\nindex 0000000..8e8e915\n--- /dev/null\n+++ b/news/167.bugfix\n@@ -0,0 +1,2 @@\n+Fixed ``$PYTHONSTARTUP`` file support for the ``debug`` command under Python 3\n+[dataflake]\ndiff --git a/src/plone/recipe/zope2instance/ctl.py b/src/plone/recipe/zope2instance/ctl.py\nindex 75ae39c..560e1e0 100644\n--- a/src/plone/recipe/zope2instance/ctl.py\n+++ b/src/plone/recipe/zope2instance/ctl.py\n@@ -796,11 +796,15 @@ def do_debug(self, arg):\n         interactive_startup = (\n             "import os;"\n             "os.path.exists(os.environ.get(\'PYTHONSTARTUP\', \'\')) "\n-            "and execfile(os.environ[\'PYTHONSTARTUP\']); del os;"\n+            "and %s; del os;"\n         )\n+        if six.PY2:\n+            exec_call = "execfile(os.environ[\'PYTHONSTARTUP\'])"\n+        else:\n+            exec_call = "exec(open(os.environ[\'PYTHONSTARTUP\']).read())"\n         cmdline = self.get_startup_cmd(\n             self.options.python,\n-            interactive_startup,\n+            interactive_startup % exec_call,\n             pyflags=\'-i\',\n         )\n         print(\'Starting debugger (the name "app" is bound to the top-level \'\n'

Repository: plone.recipe.zope2instance


Branch: refs/heads/master
Date: 2021-03-22T11:29:00+01:00
Author: Jens Vagelpohl (dataflake) <jens@netz.ooo>
Commit: https://github.com/plone/plone.recipe.zope2instance/commit/047d7de9d41cdf00446f25d61621db2b79a53d35

Merge pull request #168 from plone/dataflake/issue_167

Fix `$PYTHONSTARTUP` file support for the debug command under Python 3

Files changed:
A news/167.bugfix
M src/plone/recipe/zope2instance/ctl.py

b'diff --git a/news/167.bugfix b/news/167.bugfix\nnew file mode 100644\nindex 0000000..8e8e915\n--- /dev/null\n+++ b/news/167.bugfix\n@@ -0,0 +1,2 @@\n+Fixed ``$PYTHONSTARTUP`` file support for the ``debug`` command under Python 3\n+[dataflake]\ndiff --git a/src/plone/recipe/zope2instance/ctl.py b/src/plone/recipe/zope2instance/ctl.py\nindex 75ae39c..560e1e0 100644\n--- a/src/plone/recipe/zope2instance/ctl.py\n+++ b/src/plone/recipe/zope2instance/ctl.py\n@@ -796,11 +796,15 @@ def do_debug(self, arg):\n         interactive_startup = (\n             "import os;"\n             "os.path.exists(os.environ.get(\'PYTHONSTARTUP\', \'\')) "\n-            "and execfile(os.environ[\'PYTHONSTARTUP\']); del os;"\n+            "and %s; del os;"\n         )\n+        if six.PY2:\n+            exec_call = "execfile(os.environ[\'PYTHONSTARTUP\'])"\n+        else:\n+            exec_call = "exec(open(os.environ[\'PYTHONSTARTUP\']).read())"\n         cmdline = self.get_startup_cmd(\n             self.options.python,\n-            interactive_startup,\n+            interactive_startup % exec_call,\n             pyflags=\'-i\',\n         )\n         print(\'Starting debugger (the name "app" is bound to the top-level \'\n'

