Repository: plone.restapi


Branch: refs/heads/main
Date: 2024-04-01T22:17:00-07:00
Author: Hrittik (Hrittik20) <49366463+Hrittik20@users.noreply.github.com>
Commit: https://github.com/plone/plone.restapi/commit/5cf1418e928f143ef1b42fdc3e4ed72a3126e9dd

Fix password reset when using email as login (#1767)

* Fix password reset when using email as login

* Update test fail

* Fix black build

---------

Co-authored-by: Your Name &lt;you@example.com&gt;

Files changed:
A news/943.bugfix
M src/plone/restapi/services/users/add.py

b'diff --git a/news/943.bugfix b/news/943.bugfix\nnew file mode 100644\nindex 000000000..8a04b5f28\n--- /dev/null\n+++ b/news/943.bugfix\n@@ -0,0 +1 @@\n+Fixed password reset issue by replacing `username` with `target_user` to correctly authenticate using email. @Hrittik20\n\\ No newline at end of file\ndiff --git a/src/plone/restapi/services/users/add.py b/src/plone/restapi/services/users/add.py\nindex 2750d401f..b0136a215 100644\n--- a/src/plone/restapi/services/users/add.py\n+++ b/src/plone/restapi/services/users/add.py\n@@ -341,7 +341,9 @@ def update_password(self, data):\n                 )\n \n             check_password_auth = pas.authenticate(\n-                username, old_password.encode("utf-8"), self.request\n+                target_user.getUser().getUserName(),\n+                old_password.encode("utf-8"),\n+                self.request,\n             )\n             if not check_password_auth:\n                 return self._error(\n'

